1D array

In [12]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)


[1 2 3 4 5]


2D Array

In [ ]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Multi dimensional Array

In [ ]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

"""
same as 2d array write in row and column form
"""

[[1 2 3]
 [4 5 6]
 [7 8 9]]


'\nsame as 2d array write in row and column form\n'

In [ ]:
import numpy as np
arr=np.array([1,2,4,5])
print(arr)

[1 2 4 5]


with default value(zero shape)

In [ ]:
import numpy as np
zero=np.zeros(3)
print(zero)

[0. 0. 0.]


for ones shape

In [ ]:
import numpy as np
one=np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


full shape value

In [ ]:
import numpy as np
fullid_array=np.full((3,4),7)
print(fullid_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


Creating sequence of numbers in numpy<br>
Arrange<br>
Arrangs start stop step

In [10]:
import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


Create identity matrix
eye size

In [11]:
import numpy as np
iden_array=np.eye(4)
print(iden_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


| Function      | Purpose                     | Example    | Output shape |
| ------------- | --------------------------- | ---------- | ------------ |
| `np.array()`  | Make array from list        | `[1,2,3]`  | same as list |
| `np.zeros()`  | All elements = 0            | `(2,3)`    | 2×3          |
| `np.ones()`   | All elements = 1            | `(3,2)`    | 3×2          |
| `np.full()`   | All elements = custom value | `(2,3), 5` | 2×3          |
| `np.arange()` | Range of numbers            | `(1,10,2)` | 1D           |
| `np.eye()`    | Identity matrix             | `(3)`      | 3×3          |
