### **1. Indexing**

Indexing is used to access a single element from an array using its position.

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])    # Output: 30
```

---

### **2. Slicing**

Slicing is used to get a part of the array.

```python
print(arr[1:4])  # Output: [20 30 40]
```

---

### **3. Fancy Indexing**

Fancy indexing allows us to access multiple elements using a list of indices.

```python
indices = [0, 2, 4]
print(arr[indices])   # Output: [10 30 50]
```

---

### **4. Boolean Masking**

Boolean masking selects elements based on a condition.

```python
mask = arr > 25
print(arr[mask])   # Output: [30 40 50]
```

---



In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr[1:4])

[1 2 3 4 5]
[2 3 4]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr[1:4])
print(arr[::2])
print(arr[1::2])
print(arr[::-1])
print(arr[:4])

[1 2 3 4 5 6]
[2 3 4]
[1 3 5]
[2 4 6]
[6 5 4 3 2 1]
[1 2 3 4]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[[1,3,5]])

[2 4 6]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])

[4 5 6]
